### ISSUE TITLE
Add profile page so users can set name, biography, affiliation, etc.

### ISSUE THREAD

**Issue by rmarow** [nsidc/usaon-vta-survey#27]
We want the user to create a profile when they initially log in to the survey. Potentially with google SSO or github SSO.
```[tasklist]
### Tasks
- [x] ensure the profile database fields match the glossary
- [ ] https://github.com/nsidc/usaon-vta-survey/issues/28
- [ ] Ensure all new features comply with [user interface design doc](https://docs.google.com/presentation/d/1TW5oS7dcM9w7Jze4Wey_TozGvwvB0IHjF4bRx8TU-O8/edit#slide=id.g1c127e95d9a_0_56)
```

**Comment by rmarow** [comment]
github may be nice because it pushes people onto the platform. Google advantage is that it's more widely used and already incorporated into the project in some ways.

**Comment by rmarow** [comment]
new branch for profile page: https://github.com/nsidc/usaon-vta-survey/tree/profile_page
