### ISSUE TITLE
Ensure data model reflects the current state of the glossary

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-survey#38]
The glossary in `usaon-vta-docs` project has seen some changes, but our SQLAlchemy data model hasn't reflected them yet.
```[tasklist]
### Tasks
- [ ] https://github.com/nsidc/usaon-vta-survey/issues/40
- [x] Add user table
- [x] Add role table
```

**Comment by rmarow** [comment]
Scope not clearly defined - going to open a milestone

**Comment by MattF-NSIDC** [comment]
https://github.com/nsidc/usaon-vta-survey/issues/103
